events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream frontend {
        server web_frontend:3000;
    }

    upstream backend {
        server api_backend:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Frontend
        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend/api/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Hỗ trợ SSE (Streaming cho AI Chatbot)
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 600s;
        }

        # Backend Static files (Forms, Uploads)
        location /static/ {
            proxy_pass http://backend/static/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}
